name: Deploy to Staging

on:
  push:
    branches: [develop]
  workflow_dispatch:

concurrency:
  group: staging-deployment
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Fly.io (Staging)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: staging
      url: https://bt-log-viewer-staging.fly.dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          flyctl deploy \
            --config infra/fly.staging.toml \
            --app bt-log-viewer-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
