name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: production-deployment
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Fly.io (Production)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: production
      url: https://bt-log-viewer.fly.dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          flyctl deploy \
            --config infra/fly.production.toml \
            --app bt-log-viewer-prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
